#!/usr/bin/env python3
"""
Change Reporter for Navigator Simplification Skill

Generates human-readable reports of simplification changes.

Usage:
    python3 change_reporter.py --changes '[{"type": "nested_ternary", ...}]'
    python3 change_reporter.py --changes-file changes.json --format markdown
"""

import argparse
import json
from typing import Any
from datetime import datetime


def categorize_changes(changes: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Categorize changes by type."""
    categories = {
        "clarity": [],
        "nesting": [],
        "naming": [],
        "patterns": [],
        "other": []
    }

    type_to_category = {
        "nested_ternary_transform": "clarity",
        "nested_ternary": "clarity",
        "deep_nesting_warning": "nesting",
        "deep_nesting": "nesting",
        "unclear_name": "naming",
        "unclear_naming": "naming",
        "redundant_boolean": "patterns",
        "redundant_comparison": "patterns",
        "long_function": "patterns"
    }

    for change in changes:
        change_type = change.get("type", "unknown")
        category = type_to_category.get(change_type, "other")
        categories[category].append(change)

    return {k: v for k, v in categories.items() if v}


def format_markdown(
    changes: list[dict[str, Any]],
    file_info: dict[str, Any] = None
) -> str:
    """Format changes as Markdown report."""
    output = []

    # Header
    output.append("# Code Simplification Report")
    output.append("")
    output.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    output.append("")

    # File info
    if file_info:
        output.append("## File Information")
        output.append("")
        output.append(f"- **File**: `{file_info.get('file', 'unknown')}`")
        output.append(f"- **Changes**: {len(changes)}")
        if 'complexity_score' in file_info:
            output.append(f"- **Complexity Score**: {file_info['complexity_score']}/10")
        output.append("")

    # Summary
    categories = categorize_changes(changes)

    output.append("## Summary")
    output.append("")
    output.append("| Category | Count |")
    output.append("|----------|-------|")

    category_labels = {
        "clarity": "Clarity improvements",
        "nesting": "Nesting reduction",
        "naming": "Naming improvements",
        "patterns": "Pattern consolidation",
        "other": "Other changes"
    }

    for cat, cat_changes in categories.items():
        label = category_labels.get(cat, cat)
        output.append(f"| {label} | {len(cat_changes)} |")

    output.append("")

    # Detailed changes
    output.append("## Changes")
    output.append("")

    for cat, cat_changes in categories.items():
        if not cat_changes:
            continue

        label = category_labels.get(cat, cat)
        output.append(f"### {label}")
        output.append("")

        for i, change in enumerate(cat_changes, 1):
            line = change.get("line", "?")
            change_type = change.get("type", "unknown")

            output.append(f"**{i}. Line {line}**: `{change_type}`")

            if change.get("suggestion"):
                output.append(f"- Suggestion: {change['suggestion']}")

            if change.get("original") and change.get("replacement"):
                output.append("")
                output.append("```diff")
                output.append(f"- {change['original']}")
                output.append(f"+ {change['replacement']}")
                output.append("```")

            output.append("")

    # Footer
    output.append("---")
    output.append("")
    output.append("*Generated by Navigator Simplification Skill*")

    return "\n".join(output)


def format_text(
    changes: list[dict[str, Any]],
    file_info: dict[str, Any] = None
) -> str:
    """Format changes as plain text report."""
    output = []

    output.append("=" * 60)
    output.append("CODE SIMPLIFICATION REPORT")
    output.append("=" * 60)
    output.append("")

    if file_info:
        output.append(f"File: {file_info.get('file', 'unknown')}")
        output.append(f"Changes: {len(changes)}")
        output.append("")

    categories = categorize_changes(changes)

    output.append("SUMMARY:")
    output.append("-" * 40)

    category_labels = {
        "clarity": "Clarity improvements",
        "nesting": "Nesting reduction",
        "naming": "Naming improvements",
        "patterns": "Pattern consolidation",
        "other": "Other changes"
    }

    for cat, cat_changes in categories.items():
        label = category_labels.get(cat, cat)
        output.append(f"  {label}: {len(cat_changes)}")

    output.append("")
    output.append("DETAILS:")
    output.append("-" * 40)

    for change in changes:
        line = change.get("line", "?")
        change_type = change.get("type", "unknown")

        output.append(f"  Line {line}: {change_type}")

        if change.get("suggestion"):
            output.append(f"    -> {change['suggestion']}")

        if change.get("original") and change.get("replacement"):
            output.append(f"    Before: {change['original'][:40]}...")
            output.append(f"    After:  {change['replacement'][:40]}...")

        output.append("")

    return "\n".join(output)


def format_json(
    changes: list[dict[str, Any]],
    file_info: dict[str, Any] = None
) -> str:
    """Format changes as JSON."""
    report = {
        "generated": datetime.now().isoformat(),
        "file_info": file_info,
        "categories": categorize_changes(changes),
        "changes": changes,
        "total_changes": len(changes)
    }
    return json.dumps(report, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Generate simplification change report")
    parser.add_argument("--changes", help="JSON array of changes")
    parser.add_argument("--changes-file", help="Path to JSON file with changes")
    parser.add_argument("--file-info", help="JSON object with file information")
    parser.add_argument("--format", choices=["markdown", "text", "json"], default="markdown")

    args = parser.parse_args()

    # Load changes
    if args.changes:
        changes = json.loads(args.changes)
    elif args.changes_file:
        with open(args.changes_file) as f:
            data = json.load(f)
            if isinstance(data, list):
                changes = data
            else:
                changes = data.get("changes", data.get("issues", []))
    else:
        print("Error: Must provide --changes or --changes-file")
        return

    # Load file info
    file_info = None
    if args.file_info:
        file_info = json.loads(args.file_info)

    # Format output
    if args.format == "markdown":
        print(format_markdown(changes, file_info))
    elif args.format == "text":
        print(format_text(changes, file_info))
    else:
        print(format_json(changes, file_info))


if __name__ == "__main__":
    main()
